version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_DATABASE: healthtracker
  app:
    build: .
    ports: ["8080:8080"]
    environment:
      MONGODB_URI: mongodb://mongo:27017/healthtracker
      JWT_SIGNING_SECRET: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbi11c2VyIiwiaWF0IjoxNzYwMzA3MTY4LCJleHAiOjE3NjAzMTA3NjgsImlzQWRtaW4iOnRydWV9.amHsNi1naOF9A-Lx7NipSt7bZV-taiwIhKmpmYMY9Ks"
    depends_on: [mongo]
