server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/healthtracker}
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
health:
  check:
    tick-ms: 60000
resilience4j:
  retry:
    instances:
      healthCheckRetry:
        maxAttempts: 2
        waitDuration: 200ms
  circuitbreaker:
    instances:
      healthCheckCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
